# Generated by Django 5.2.4 on 2026-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_Number', models.CharField(max_length=12, unique=True)),
                ('Raised_By', models.CharField(max_length=30)),
                ('Raised_At', models.DateField(auto_now=True)),
                ('Short_Description', models.TextField(max_length=30)),
                ('Complete_Description', models.TextField(max_length=100)),
                ('Ticket_Status', models.CharField(choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('User_Contact', models.CharField(max_length=12)),
                ('Issue_Category', models.CharField(choices=[('access', 'Access Issue'), ('request', 'Item Request'), ('hardware', 'Hardware Issue'), ('general', 'General Issue')], max_length=20)),
                ('Working_Notes', models.TextField()),
                ('Resolution_Notes', models.TextField()),
            ],
        ),
    ]
