# Generated by Django 5.2.17 on 2026-09-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Issue_Category',
            field=models.CharField(choices=[('access', 'Access Issue'), ('hardware', 'Hardware Issue'), ('general', 'General Issue')], max_length=20),
        ),
    ]
