# Generated by Django 5.2.17 on 2026-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Creation', '0002_alter_ticket_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Issue_Category',
            field=models.CharField(choices=[('Access Issue', 'Access Issue'), ('Item Request', 'Item Request'), ('Hardware Issue', 'Hardware Issue'), ('General Issue', 'General Issue')], max_length=20),
        ),
    ]
