# Generated by Django 5.2.17 on 2026-09-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Creation', '0003_alter_ticket_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_Status',
            field=models.CharField(choices=[('New', 'New'), ('Closed', 'Closed'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved')], default='NEW', max_length=20),
        ),
    ]
