# Generated by Django 5.2.17 on 2026-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_Creation', '0004_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_Status',
            field=models.CharField(choices=[('New', 'NEW'), ('Closed', 'CLOSED'), ('In Progress', 'IN_PROGRESS'), ('On Hold', 'ON_HOLD'), ('Resolved', 'RESOLVED')], default='NEW', max_length=20),
        ),
    ]
